spring.application.name=fileOperations


server.port=9790
spring.datasource.url=jdbc:postgresql://localhost:5432/file-operations
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

file.base.directory=D://fileOperation